# Generated by Django 2.1.4 on 2019-02-03 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20190203_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='closed_answer',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.Choice'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='open_answer',
            field=models.CharField(blank=True, editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='poll.Question'),
        ),
    ]
